package io.github.some_example_name.assets;

import com.badlogic.gdx.assets.AssetManager;
import com.badlogic.gdx.assets.loaders.resolvers.InternalFileHandleResolver;
import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.utils.Disposable;

/** Central asset gateway. Singleton — one {@link AssetManager} for the whole app. */
public final class GameAssets implements Disposable {
    public static final String PROCEDURAL_VISUALS = "generated/procedural-visuals";
    public static final String SFX_BALL_HIT  = "Sounds/Effects/Ball Hit Audio.mp3";
    public static final String SFX_TABLE_HIT = "Sounds/Effects/Table Hit.mp3";
    // Generated by tools/audio/generate_audio.py
    public static final String SFX_UI_CLICK  = "Sounds/Effects/ui_click.wav";
    public static final String SFX_UI_HOVER  = "Sounds/Effects/ui_hover.wav";
    public static final String SFX_ITEM_USE  = "Sounds/Effects/item_use.wav";
    public static final String SFX_LIFE_LOST = "Sounds/Effects/life_lost.wav";
    public static final String SFX_FLY_BUZZ  = "Sounds/Effects/fly_buzz.wav";
    public static final String MUSIC_BG      = "Sounds/Music/bunker_bar.wav";

    private static GameAssets instance;

    /** Lazily-created singleton. Call sites normally reach this via {@code GameContext#getAssets()}. */
    public static GameAssets instance() {
        if (instance == null) {
            instance = new GameAssets();
        }
        return instance;
    }

    private final AssetManager assetManager;
    private boolean queued;

    private GameAssets() {
        InternalFileHandleResolver resolver = new InternalFileHandleResolver();
        assetManager = new AssetManager(resolver);
        assetManager.setLoader(ProceduralAssets.class, new ProceduralAssetsLoader(resolver));
    }

    public void queueCoreAssets() {
        if (queued) {
            return;
        }
        queued = true;
        assetManager.load(PROCEDURAL_VISUALS, ProceduralAssets.class);
        assetManager.load(SFX_BALL_HIT,  Sound.class);
        assetManager.load(SFX_TABLE_HIT, Sound.class);
        assetManager.load(SFX_UI_CLICK,  Sound.class);
        assetManager.load(SFX_UI_HOVER,  Sound.class);
        assetManager.load(SFX_ITEM_USE,  Sound.class);
        assetManager.load(SFX_LIFE_LOST, Sound.class);
        assetManager.load(SFX_FLY_BUZZ,  Sound.class);
        assetManager.load(MUSIC_BG,      Music.class);
    }

    public boolean update() {
        return assetManager.update();
    }

    public float getProgress() {
        return assetManager.getProgress();
    }

    public boolean isReady() {
        return queued
            && assetManager.isLoaded(PROCEDURAL_VISUALS)
            && assetManager.isLoaded(SFX_BALL_HIT)
            && assetManager.isLoaded(SFX_TABLE_HIT)
            && assetManager.isLoaded(SFX_UI_CLICK)
            && assetManager.isLoaded(SFX_UI_HOVER)
            && assetManager.isLoaded(SFX_ITEM_USE)
            && assetManager.isLoaded(SFX_LIFE_LOST)
            && assetManager.isLoaded(SFX_FLY_BUZZ)
            && assetManager.isLoaded(MUSIC_BG);
    }

    public int getLoadedAssetsCount() {
        return assetManager.getLoadedAssets();
    }

    public int getQueuedAssetsCount() {
        return assetManager.getQueuedAssets();
    }

    public String getLoadingStageLabel() {
        if (!assetManager.isLoaded(PROCEDURAL_VISUALS)) {
            return "Building procedural world visuals";
        }
        return "Finalizing startup";
    }

    public ProceduralAssets getProceduralAssets() {
        return assetManager.get(PROCEDURAL_VISUALS, ProceduralAssets.class);
    }

    public Sound getBallHitSfx()    { return assetManager.get(SFX_BALL_HIT,  Sound.class); }
    public Sound getTableHitSfx()   { return assetManager.get(SFX_TABLE_HIT, Sound.class); }
    public Sound getUiClickSfx()    { return assetManager.get(SFX_UI_CLICK,  Sound.class); }
    public Sound getUiHoverSfx()    { return assetManager.get(SFX_UI_HOVER,  Sound.class); }
    public Sound getItemUseSfx()    { return assetManager.get(SFX_ITEM_USE,  Sound.class); }
    public Sound getLifeLostSfx()   { return assetManager.get(SFX_LIFE_LOST, Sound.class); }
    public Sound getFlyBuzzSfx()    { return assetManager.get(SFX_FLY_BUZZ,  Sound.class); }
    public Music getBackgroundMusic() { return assetManager.get(MUSIC_BG,    Music.class); }

    @Override
    public void dispose() {
        assetManager.dispose();
        if (instance == this) {
            instance = null; // a relaunch in the same JVM gets a fresh instance
        }
    }
}
